############# Chinese navigation ##############

# main menu
[[main]]
name = "博物馆概览"
url = "/"
weight = 1

[[main]]
name = "香水历史"
url = "/history"
weight = 2

[[main]]
name = "经典香水"
url = "/collection"
weight = 3

[[main]]
name = "香料"
url = "/fragrances"
weight = 4

[[main]]
name = "现代香展示区"
url = "/area"
weight = 5

[[main]]
name = "关于我们"
url = "/contact"
weight = 6

# footer menu
# [[footer]]
#name = "About"
#url = "/about"
#weight = 1
